// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaFlota;

#nullable disable

namespace SistemaFlota.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260805230535_AgregarCamposTemporalesConversacion")]
    partial class AgregarCamposTemporalesConversacion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SistemaFlota.Auditoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Detalle")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("RegistroId")
                        .HasColumnType("int");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Auditorias");
                });

            modelBuilder.Entity("SistemaFlota.Autorizacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CantidadClientes")
                        .HasColumnType("int");

                    b.Property<int>("ConductorId")
                        .HasColumnType("int");

                    b.Property<string>("DescripcionCarga")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DestinoCompleto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Escalado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EstadoLlegada")
                        .HasColumnType("longtext");

                    b.Property<string>("EstadoVehiculoLlegada")
                        .HasColumnType("longtext");

                    b.Property<string>("FacturasClientes")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("FechaBodega")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaConfirmacionLlegada")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaFacturacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaPorteria")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaReporteLlegada")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaSalidaReal")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaUltimoRecordatorio")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FirmaBodega")
                        .HasColumnType("longtext");

                    b.Property<string>("FirmaFacturacion")
                        .HasColumnType("longtext");

                    b.Property<string>("FirmaPorteria")
                        .HasColumnType("longtext");

                    b.Property<string>("FirmaPorteriaLlegada")
                        .HasColumnType("longtext");

                    b.Property<string>("FotoOdometroLlegada")
                        .HasColumnType("longtext");

                    b.Property<int>("IntentosRecordatorio")
                        .HasColumnType("int");

                    b.Property<int?>("KilometrajeFinal")
                        .HasColumnType("int");

                    b.Property<string>("NovedadesViaje")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroGuia")
                        .HasColumnType("longtext");

                    b.Property<string>("ObservacionBodega")
                        .HasColumnType("longtext");

                    b.Property<string>("ObservacionFacturacion")
                        .HasColumnType("longtext");

                    b.Property<string>("ObservacionPorteria")
                        .HasColumnType("longtext");

                    b.Property<string>("ObservacionPorteriaLlegada")
                        .HasColumnType("longtext");

                    b.Property<decimal>("PesoKilos")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("TipoVuelta")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioBodega")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioFacturacion")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioPorteria")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioPorteriaLlegada")
                        .HasColumnType("longtext");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConductorId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("Autorizaciones");
                });

            modelBuilder.Entity("SistemaFlota.CambioRuta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("AutorizacionId")
                        .HasColumnType("int");

                    b.Property<string>("AutorizadoPor")
                        .HasColumnType("longtext");

                    b.Property<int>("ConductorId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("FechaAutorizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MotivoCambio")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NuevaRuta")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ObservacionAut")
                        .HasColumnType("longtext");

                    b.Property<string>("RutaOriginal")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AutorizacionId");

                    b.HasIndex("ConductorId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("CambiosRuta");
                });

            modelBuilder.Entity("SistemaFlota.Capacitacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Aprobado")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ConductorId")
                        .HasColumnType("int");

                    b.Property<string>("Documento")
                        .HasColumnType("longtext");

                    b.Property<int?>("DuracionHoras")
                        .HasColumnType("int");

                    b.Property<string>("Entidad")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Instructor")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Observaciones")
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ConductorId");

                    b.ToTable("Capacitaciones");
                });

            modelBuilder.Entity("SistemaFlota.ChecklistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TipoVehiculoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TipoVehiculoId");

                    b.ToTable("ChecklistItems");
                });

            modelBuilder.Entity("SistemaFlota.Conductor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Arl")
                        .HasColumnType("longtext");

                    b.Property<string>("CategoriaLicencia")
                        .HasColumnType("longtext");

                    b.Property<string>("Cedula")
                        .HasColumnType("longtext");

                    b.Property<string>("ClasificacionVehiculo")
                        .HasColumnType("longtext");

                    b.Property<string>("ContactoEmergencia")
                        .HasColumnType("longtext");

                    b.Property<string>("Direccion")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Eps")
                        .HasColumnType("longtext");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("FechaExpedicionLicencia")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaVencimientoLicencia")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FondoPension")
                        .HasColumnType("longtext");

                    b.Property<string>("Foto")
                        .HasColumnType("longtext");

                    b.Property<string>("Licencia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TelefonoEmergencia")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoSangre")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoVehiculo")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Conductores");
                });

            modelBuilder.Entity("SistemaFlota.ConfiguracionEmpresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ColorCorporativo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Logo")
                        .HasColumnType("longtext");

                    b.Property<string>("NIT")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NombreEmpresa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SitioWeb")
                        .HasColumnType("longtext");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ConfiguracionEmpresa");
                });

            modelBuilder.Entity("SistemaFlota.ContactoNotificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroWhatsApp")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("RecibeIncidentes")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("RecibeInspecciones")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("RecibeLiberaciones")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("RecibePedidos")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("ContactosNotificacion");
                });

            modelBuilder.Entity("SistemaFlota.CosteFlete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Alimentacion")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("AutorizacionId")
                        .HasColumnType("int");

                    b.Property<decimal>("CargueMateriales")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Combustible")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("DescarguesMcia")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaVerificacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FirmaVerificacion")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Hospedaje")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Parqueos")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Peajes")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Varios")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("VerificadoPor")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AutorizacionId");

                    b.ToTable("CostosFletes");
                });

            modelBuilder.Entity("SistemaFlota.DocumentoGeneral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ArchivoUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<string>("Extension")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaSubida")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("TamanoBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("DocumentosGenerales");
                });

            modelBuilder.Entity("SistemaFlota.DocumentoVehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ArchivoUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<string>("Extension")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaSubida")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VehiculoId");

                    b.ToTable("DocumentosVehiculo");
                });

            modelBuilder.Entity("SistemaFlota.EncuestaFatiga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ConductorId")
                        .HasColumnType("int");

                    b.Property<bool>("DespertoVariasVeces")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("DificultadConcentracion")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("DurmioMenos7Horas")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("MedicamentoSueno")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("longtext");

                    b.Property<string>("OtraObservacion")
                        .HasColumnType("longtext");

                    b.Property<string>("RegistradoPor")
                        .HasColumnType("longtext");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("SienteCansancio")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConductorId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("EncuestasFatiga");
                });

            modelBuilder.Entity("SistemaFlota.ExamenMedico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ConductorId")
                        .HasColumnType("int");

                    b.Property<string>("Documento")
                        .HasColumnType("longtext");

                    b.Property<string>("Entidad")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaExamen")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Medico")
                        .HasColumnType("longtext");

                    b.Property<string>("Observaciones")
                        .HasColumnType("longtext");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TipoExamen")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ConductorId");

                    b.ToTable("ExamenesMedicos");
                });

            modelBuilder.Entity("SistemaFlota.FormatoFGC008", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AccionesTomadas")
                        .HasColumnType("longtext");

                    b.Property<decimal>("CantidadOP")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("CantidadReal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Cliente")
                        .HasColumnType("longtext");

                    b.Property<bool>("DefectosSI")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Despachado")
                        .HasColumnType("longtext");

                    b.Property<bool>("EmbalajeSI")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EtiquetasSI")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaRevision")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FirmaDigital")
                        .HasColumnType("longtext");

                    b.Property<string>("FotoEvidencia")
                        .HasColumnType("longtext");

                    b.Property<bool>("ListoBodega")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("OrdenProduccion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Referencia")
                        .HasColumnType("longtext");

                    b.Property<string>("RevisadoPor")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("FormatoFGC008");
                });

            modelBuilder.Entity("SistemaFlota.Incidente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("AutorizacionId")
                        .HasColumnType("int");

                    b.Property<int>("ConductorId")
                        .HasColumnType("int");

                    b.Property<string>("DescripcionDetallada")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaReporte")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaRevision")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Fotos")
                        .HasColumnType("longtext");

                    b.Property<double?>("Latitud")
                        .HasColumnType("double");

                    b.Property<double?>("Longitud")
                        .HasColumnType("double");

                    b.Property<string>("ObservacionRevision")
                        .HasColumnType("longtext");

                    b.Property<string>("RevisadoPor")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoIncidente")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UbicacionGPS")
                        .HasColumnType("longtext");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AutorizacionId");

                    b.HasIndex("ConductorId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("Incidentes");
                });

            modelBuilder.Entity("SistemaFlota.InfraccionConductor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ConductorId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<string>("Documento")
                        .HasColumnType("longtext");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaInfraccion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Lugar")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroComparendo")
                        .HasColumnType("longtext");

                    b.Property<string>("Observaciones")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoInfraccion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Valor")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("ConductorId");

                    b.ToTable("Infracciones");
                });

            modelBuilder.Entity("SistemaFlota.Inspeccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ConductorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FirmaCondutor")
                        .HasColumnType("longtext");

                    b.Property<string>("FotoOdometro")
                        .HasColumnType("longtext");

                    b.Property<int>("Kilometraje")
                        .HasColumnType("int");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("int");

                    b.Property<bool?>("WhatsAppEnviado")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("ConductorId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("Inspecciones");
                });

            modelBuilder.Entity("SistemaFlota.InspeccionDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ChecklistItemId")
                        .HasColumnType("int");

                    b.Property<string>("DescripcionItem")
                        .HasColumnType("longtext");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FotoEvidencia")
                        .HasColumnType("longtext");

                    b.Property<int>("InspeccionId")
                        .HasColumnType("int");

                    b.Property<string>("Observacion")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ChecklistItemId");

                    b.HasIndex("InspeccionId");

                    b.ToTable("InspeccionDetalles");
                });

            modelBuilder.Entity("SistemaFlota.InventarioRuta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Archivo")
                        .HasColumnType("longtext");

                    b.Property<string>("CreadoPor")
                        .HasColumnType("longtext");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("InventarioRutas");
                });

            modelBuilder.Entity("SistemaFlota.Mantenimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("CostoManoObra")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("CostoRepuestos")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("CostoTotal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaEntrada")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaSalida")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaSiguiente")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Fotos")
                        .HasColumnType("longtext");

                    b.Property<int>("KilometrajeEntrada")
                        .HasColumnType("int");

                    b.Property<int?>("KilometrajeSiguiente")
                        .HasColumnType("int");

                    b.Property<string>("NombreTaller")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Observaciones")
                        .HasColumnType("longtext");

                    b.Property<string>("RepuestosUtilizados")
                        .HasColumnType("longtext");

                    b.Property<string>("TecnicoResponsable")
                        .HasColumnType("longtext");

                    b.Property<string>("TelefonoTaller")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoMantenimiento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TrabajosRealizados")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VehiculoId");

                    b.ToTable("Mantenimientos");
                });

            modelBuilder.Entity("SistemaFlota.Models.Cajon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cajones");
                });

            modelBuilder.Entity("SistemaFlota.Models.CaracteristicaFormato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<int>("TipoFormatoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TipoFormatoId");

                    b.ToTable("CaracteristicasFormato");
                });

            modelBuilder.Entity("SistemaFlota.Models.ConversacionFlotaChat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DestinoTemp")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FlotaChatUsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("Paso")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("VehiculoIdTemp")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ConversacionesFlotaChat");
                });

            modelBuilder.Entity("SistemaFlota.Models.CyreleFoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CyreleRegistroId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CyreleRegistroId");

                    b.ToTable("CyreleFotos");
                });

            modelBuilder.Entity("SistemaFlota.Models.CyreleRegistro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CajonId")
                        .HasColumnType("int");

                    b.Property<int>("CreadoPor")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Foto")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("ModificadoPor")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CajonId");

                    b.ToTable("CyreleRegistros");
                });

            modelBuilder.Entity("SistemaFlota.Models.OpcionFormulario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<int?>("TipoFormatoId")
                        .HasColumnType("int");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("TipoFormatoId");

                    b.ToTable("OpcionesFormulario");
                });

            modelBuilder.Entity("SistemaFlota.Models.OrdenProduccionExterna", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CantidadOP")
                        .HasColumnType("int");

                    b.Property<string>("Cliente")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("FechaImportacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NumeroOP")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Referencia")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("OrdenesProduccionExternas");
                });

            modelBuilder.Entity("SistemaFlota.Models.RegistroFormatoCalidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CargoFirma")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Cliente")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ExplicacionNoLiberado")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaRevision")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FirmaDigital")
                        .HasColumnType("longtext");

                    b.Property<string>("Hora")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Maquina")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Operarios")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("OrdenProduccion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ProduccionKgHora")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool?>("PuedeLiberarse")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Referencia")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ResultadosJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RevisadoPor")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("TipoFormatoId")
                        .HasColumnType("int");

                    b.Property<string>("VariablesCriticasJson")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("TipoFormatoId");

                    b.ToTable("RegistrosFormatoCalidad");
                });

            modelBuilder.Entity("SistemaFlota.Models.SeguimientoRrhh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<short>("Anio")
                        .HasColumnType("smallint");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Areas")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("CreadoPor")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("FactorRiesgo")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaEjecucion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaSeguimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Fuente")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<byte>("Mes")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int?>("ModificadoPor")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasColumnType("longtext");

                    b.Property<string>("PlanAccionSugerido")
                        .HasColumnType("longtext");

                    b.Property<string>("Prioridad")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Responsable")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.ToTable("SeguimientosRrhh");
                });

            modelBuilder.Entity("SistemaFlota.Models.SeguimientoRrhhFoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaSubida")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("SeguimientoId")
                        .HasColumnType("int");

                    b.Property<string>("TipoFoto")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("SeguimientoId");

                    b.ToTable("SeguimientosRrhhFotos");
                });

            modelBuilder.Entity("SistemaFlota.Models.TipoFormatoCalidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("TieneVariablesCriticas")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("TiposFormatoCalidad");
                });

            modelBuilder.Entity("SistemaFlota.NotaTrazabilidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cliente")
                        .HasColumnType("longtext");

                    b.Property<string>("Conductor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("FacturaEntregada")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NumeroNota")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Observacion")
                        .HasColumnType("longtext");

                    b.Property<int>("TrazabilidadId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrazabilidadId");

                    b.ToTable("NotasTrazabilidad");
                });

            modelBuilder.Entity("SistemaFlota.NumeroEmergencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Observaciones")
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("NumerosEmergencia");
                });

            modelBuilder.Entity("SistemaFlota.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("FechaDespacho")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("GestionadoPor")
                        .HasColumnType("longtext");

                    b.Property<string>("Observaciones")
                        .HasColumnType("longtext");

                    b.Property<string>("Prioridad")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("VendedorNombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("SistemaFlota.PedidoReferencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal?>("CantidadKg")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("CantidadUnidades")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.ToTable("PedidoReferencias");
                });

            modelBuilder.Entity("SistemaFlota.RespuestaFlotaChat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ConductorId")
                        .HasColumnType("int");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaRecibido")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FlotaChatUsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("GrupoId")
                        .HasColumnType("int");

                    b.Property<bool>("Procesado")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("RespuestasFlotaChat");
                });

            modelBuilder.Entity("SistemaFlota.SolicitudTaller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AutorizadoPor")
                        .HasColumnType("longtext");

                    b.Property<int>("ConductorId")
                        .HasColumnType("int");

                    b.Property<string>("DescripcionProblema")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("FacturaValidada")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("FechaAutorizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaFactura")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FotoOdometro")
                        .HasColumnType("longtext");

                    b.Property<int?>("Kilometraje")
                        .HasColumnType("int");

                    b.Property<string>("NumeroFacturaTaller")
                        .HasColumnType("longtext");

                    b.Property<string>("ObservacionAut")
                        .HasColumnType("longtext");

                    b.Property<string>("ObservacionFactura")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoMantenimiento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("ValorFactura")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConductorId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("SolicitudesTaller");
                });

            modelBuilder.Entity("SistemaFlota.TipoVehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TiposVehiculo");
                });

            modelBuilder.Entity("SistemaFlota.TrazabilidadFactura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("AjusteRecibido")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("AutorizacionId")
                        .HasColumnType("int");

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Conductor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("FacturaEntregada")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FacturaRemision")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Guia")
                        .HasColumnType("longtext");

                    b.Property<string>("Novedad")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("PesoKilos")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Transportadora")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("ValorFlete")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Vehiculo")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AutorizacionId");

                    b.ToTable("TrazabilidadFacturas");
                });

            modelBuilder.Entity("SistemaFlota.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordConductores")
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("TokenExpiracion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TokenRecuperacion")
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SistemaFlota.UsuarioPermiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("EsInicio")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("PuedeCrear")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("PuedeEditar")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("PuedeEliminar")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("PuedeVer")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("UsuarioPermisos");
                });

            modelBuilder.Entity("SistemaFlota.Vehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Año")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ConductorId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Foto")
                        .HasColumnType("longtext");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tenencia")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ConductorId");

                    b.ToTable("Vehiculos");
                });

            modelBuilder.Entity("SistemaFlota.VinculacionFlotaChat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("EntidadId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaVinculacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FlotaChatUsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoEntidad")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("VinculacionesFlotaChat");
                });

            modelBuilder.Entity("SistemaFlota.Autorizacion", b =>
                {
                    b.HasOne("SistemaFlota.Conductor", "Conductor")
                        .WithMany()
                        .HasForeignKey("ConductorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaFlota.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conductor");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("SistemaFlota.CambioRuta", b =>
                {
                    b.HasOne("SistemaFlota.Autorizacion", "Autorizacion")
                        .WithMany()
                        .HasForeignKey("AutorizacionId");

                    b.HasOne("SistemaFlota.Conductor", "Conductor")
                        .WithMany()
                        .HasForeignKey("ConductorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaFlota.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autorizacion");

                    b.Navigation("Conductor");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("SistemaFlota.Capacitacion", b =>
                {
                    b.HasOne("SistemaFlota.Conductor", "Conductor")
                        .WithMany("Capacitaciones")
                        .HasForeignKey("ConductorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conductor");
                });

            modelBuilder.Entity("SistemaFlota.ChecklistItem", b =>
                {
                    b.HasOne("SistemaFlota.TipoVehiculo", "TipoVehiculo")
                        .WithMany()
                        .HasForeignKey("TipoVehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoVehiculo");
                });

            modelBuilder.Entity("SistemaFlota.CosteFlete", b =>
                {
                    b.HasOne("SistemaFlota.Autorizacion", "Autorizacion")
                        .WithMany()
                        .HasForeignKey("AutorizacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autorizacion");
                });

            modelBuilder.Entity("SistemaFlota.DocumentoVehiculo", b =>
                {
                    b.HasOne("SistemaFlota.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("SistemaFlota.EncuestaFatiga", b =>
                {
                    b.HasOne("SistemaFlota.Conductor", "Conductor")
                        .WithMany()
                        .HasForeignKey("ConductorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaFlota.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conductor");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("SistemaFlota.ExamenMedico", b =>
                {
                    b.HasOne("SistemaFlota.Conductor", "Conductor")
                        .WithMany("ExamenesMedicos")
                        .HasForeignKey("ConductorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conductor");
                });

            modelBuilder.Entity("SistemaFlota.Incidente", b =>
                {
                    b.HasOne("SistemaFlota.Autorizacion", "Autorizacion")
                        .WithMany()
                        .HasForeignKey("AutorizacionId");

                    b.HasOne("SistemaFlota.Conductor", "Conductor")
                        .WithMany()
                        .HasForeignKey("ConductorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaFlota.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autorizacion");

                    b.Navigation("Conductor");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("SistemaFlota.InfraccionConductor", b =>
                {
                    b.HasOne("SistemaFlota.Conductor", "Conductor")
                        .WithMany("Infracciones")
                        .HasForeignKey("ConductorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conductor");
                });

            modelBuilder.Entity("SistemaFlota.Inspeccion", b =>
                {
                    b.HasOne("SistemaFlota.Conductor", "Conductor")
                        .WithMany()
                        .HasForeignKey("ConductorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaFlota.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conductor");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("SistemaFlota.InspeccionDetalle", b =>
                {
                    b.HasOne("SistemaFlota.ChecklistItem", "ChecklistItem")
                        .WithMany()
                        .HasForeignKey("ChecklistItemId");

                    b.HasOne("SistemaFlota.Inspeccion", "Inspeccion")
                        .WithMany("Detalles")
                        .HasForeignKey("InspeccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChecklistItem");

                    b.Navigation("Inspeccion");
                });

            modelBuilder.Entity("SistemaFlota.Mantenimiento", b =>
                {
                    b.HasOne("SistemaFlota.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("SistemaFlota.Models.CaracteristicaFormato", b =>
                {
                    b.HasOne("SistemaFlota.Models.TipoFormatoCalidad", "TipoFormato")
                        .WithMany("Caracteristicas")
                        .HasForeignKey("TipoFormatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoFormato");
                });

            modelBuilder.Entity("SistemaFlota.Models.CyreleFoto", b =>
                {
                    b.HasOne("SistemaFlota.Models.CyreleRegistro", "Registro")
                        .WithMany("Fotos")
                        .HasForeignKey("CyreleRegistroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Registro");
                });

            modelBuilder.Entity("SistemaFlota.Models.CyreleRegistro", b =>
                {
                    b.HasOne("SistemaFlota.Models.Cajon", "Cajon")
                        .WithMany("Registros")
                        .HasForeignKey("CajonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cajon");
                });

            modelBuilder.Entity("SistemaFlota.Models.OpcionFormulario", b =>
                {
                    b.HasOne("SistemaFlota.Models.TipoFormatoCalidad", "TipoFormato")
                        .WithMany()
                        .HasForeignKey("TipoFormatoId");

                    b.Navigation("TipoFormato");
                });

            modelBuilder.Entity("SistemaFlota.Models.RegistroFormatoCalidad", b =>
                {
                    b.HasOne("SistemaFlota.Models.TipoFormatoCalidad", "TipoFormato")
                        .WithMany()
                        .HasForeignKey("TipoFormatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoFormato");
                });

            modelBuilder.Entity("SistemaFlota.Models.SeguimientoRrhhFoto", b =>
                {
                    b.HasOne("SistemaFlota.Models.SeguimientoRrhh", "Seguimiento")
                        .WithMany("Fotos")
                        .HasForeignKey("SeguimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Seguimiento");
                });

            modelBuilder.Entity("SistemaFlota.NotaTrazabilidad", b =>
                {
                    b.HasOne("SistemaFlota.TrazabilidadFactura", "Trazabilidad")
                        .WithMany()
                        .HasForeignKey("TrazabilidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trazabilidad");
                });

            modelBuilder.Entity("SistemaFlota.PedidoReferencia", b =>
                {
                    b.HasOne("SistemaFlota.Pedido", "Pedido")
                        .WithMany("Referencias")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("SistemaFlota.SolicitudTaller", b =>
                {
                    b.HasOne("SistemaFlota.Conductor", "Conductor")
                        .WithMany()
                        .HasForeignKey("ConductorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaFlota.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conductor");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("SistemaFlota.TrazabilidadFactura", b =>
                {
                    b.HasOne("SistemaFlota.Autorizacion", "Autorizacion")
                        .WithMany()
                        .HasForeignKey("AutorizacionId");

                    b.Navigation("Autorizacion");
                });

            modelBuilder.Entity("SistemaFlota.UsuarioPermiso", b =>
                {
                    b.HasOne("SistemaFlota.Usuario", "Usuario")
                        .WithMany("Permisos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaFlota.Vehiculo", b =>
                {
                    b.HasOne("SistemaFlota.Conductor", "Conductor")
                        .WithMany()
                        .HasForeignKey("ConductorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conductor");
                });

            modelBuilder.Entity("SistemaFlota.Conductor", b =>
                {
                    b.Navigation("Capacitaciones");

                    b.Navigation("ExamenesMedicos");

                    b.Navigation("Infracciones");
                });

            modelBuilder.Entity("SistemaFlota.Inspeccion", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("SistemaFlota.Models.Cajon", b =>
                {
                    b.Navigation("Registros");
                });

            modelBuilder.Entity("SistemaFlota.Models.CyreleRegistro", b =>
                {
                    b.Navigation("Fotos");
                });

            modelBuilder.Entity("SistemaFlota.Models.SeguimientoRrhh", b =>
                {
                    b.Navigation("Fotos");
                });

            modelBuilder.Entity("SistemaFlota.Models.TipoFormatoCalidad", b =>
                {
                    b.Navigation("Caracteristicas");
                });

            modelBuilder.Entity("SistemaFlota.Pedido", b =>
                {
                    b.Navigation("Referencias");
                });

            modelBuilder.Entity("SistemaFlota.Usuario", b =>
                {
                    b.Navigation("Permisos");
                });
#pragma warning restore 612, 618
        }
    }
}
