// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaFlota;

#nullable disable

namespace SistemaFlota.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260524213357_AgregaIncidentesContactos")]
    partial class AgregaIncidentesContactos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SistemaFlota.Autorizacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CantidadClientes")
                        .HasColumnType("int");

                    b.Property<int>("ConductorId")
                        .HasColumnType("int");

                    b.Property<string>("DescripcionCarga")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DestinoCompleto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("FechaBodega")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaFacturacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaPorteria")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FirmaBodega")
                        .HasColumnType("longtext");

                    b.Property<string>("FirmaFacturacion")
                        .HasColumnType("longtext");

                    b.Property<string>("FirmaPorteria")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroGuia")
                        .HasColumnType("longtext");

                    b.Property<string>("ObservacionBodega")
                        .HasColumnType("longtext");

                    b.Property<string>("ObservacionFacturacion")
                        .HasColumnType("longtext");

                    b.Property<string>("ObservacionPorteria")
                        .HasColumnType("longtext");

                    b.Property<decimal>("PesoKilos")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("TipoVuelta")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioBodega")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioFacturacion")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioPorteria")
                        .HasColumnType("longtext");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConductorId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("Autorizaciones");
                });

            modelBuilder.Entity("SistemaFlota.ChecklistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TipoVehiculoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TipoVehiculoId");

                    b.ToTable("ChecklistItems");
                });

            modelBuilder.Entity("SistemaFlota.Conductor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Foto")
                        .HasColumnType("longtext");

                    b.Property<string>("Licencia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Conductores");
                });

            modelBuilder.Entity("SistemaFlota.ContactoNotificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroWhatsApp")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("RecibeIncidentes")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("ContactosNotificacion");
                });

            modelBuilder.Entity("SistemaFlota.Incidente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("AutorizacionId")
                        .HasColumnType("int");

                    b.Property<int>("ConductorId")
                        .HasColumnType("int");

                    b.Property<string>("DescripcionDetallada")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaReporte")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaRevision")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Fotos")
                        .HasColumnType("longtext");

                    b.Property<double?>("Latitud")
                        .HasColumnType("double");

                    b.Property<double?>("Longitud")
                        .HasColumnType("double");

                    b.Property<string>("ObservacionRevision")
                        .HasColumnType("longtext");

                    b.Property<string>("RevisadoPor")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoIncidente")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UbicacionGPS")
                        .HasColumnType("longtext");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AutorizacionId");

                    b.HasIndex("ConductorId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("Incidentes");
                });

            modelBuilder.Entity("SistemaFlota.Inspeccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ConductorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FirmaCondutor")
                        .HasColumnType("longtext");

                    b.Property<string>("FotoOdometro")
                        .HasColumnType("longtext");

                    b.Property<int>("Kilometraje")
                        .HasColumnType("int");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConductorId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("Inspecciones");
                });

            modelBuilder.Entity("SistemaFlota.InspeccionDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ChecklistItemId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FotoEvidencia")
                        .HasColumnType("longtext");

                    b.Property<int>("InspeccionId")
                        .HasColumnType("int");

                    b.Property<string>("Observacion")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ChecklistItemId");

                    b.HasIndex("InspeccionId");

                    b.ToTable("InspeccionDetalles");
                });

            modelBuilder.Entity("SistemaFlota.TipoVehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TiposVehiculo");
                });

            modelBuilder.Entity("SistemaFlota.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("TokenExpiracion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TokenRecuperacion")
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SistemaFlota.UsuarioPermiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("UsuarioPermisos");
                });

            modelBuilder.Entity("SistemaFlota.Vehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Año")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ConductorId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Foto")
                        .HasColumnType("longtext");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ConductorId");

                    b.ToTable("Vehiculos");
                });

            modelBuilder.Entity("SistemaFlota.Autorizacion", b =>
                {
                    b.HasOne("SistemaFlota.Conductor", "Conductor")
                        .WithMany()
                        .HasForeignKey("ConductorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaFlota.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conductor");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("SistemaFlota.ChecklistItem", b =>
                {
                    b.HasOne("SistemaFlota.TipoVehiculo", "TipoVehiculo")
                        .WithMany()
                        .HasForeignKey("TipoVehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoVehiculo");
                });

            modelBuilder.Entity("SistemaFlota.Incidente", b =>
                {
                    b.HasOne("SistemaFlota.Autorizacion", "Autorizacion")
                        .WithMany()
                        .HasForeignKey("AutorizacionId");

                    b.HasOne("SistemaFlota.Conductor", "Conductor")
                        .WithMany()
                        .HasForeignKey("ConductorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaFlota.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autorizacion");

                    b.Navigation("Conductor");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("SistemaFlota.Inspeccion", b =>
                {
                    b.HasOne("SistemaFlota.Conductor", "Conductor")
                        .WithMany()
                        .HasForeignKey("ConductorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaFlota.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conductor");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("SistemaFlota.InspeccionDetalle", b =>
                {
                    b.HasOne("SistemaFlota.ChecklistItem", "ChecklistItem")
                        .WithMany()
                        .HasForeignKey("ChecklistItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaFlota.Inspeccion", "Inspeccion")
                        .WithMany("Detalles")
                        .HasForeignKey("InspeccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChecklistItem");

                    b.Navigation("Inspeccion");
                });

            modelBuilder.Entity("SistemaFlota.UsuarioPermiso", b =>
                {
                    b.HasOne("SistemaFlota.Usuario", "Usuario")
                        .WithMany("Permisos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaFlota.Vehiculo", b =>
                {
                    b.HasOne("SistemaFlota.Conductor", "Conductor")
                        .WithMany()
                        .HasForeignKey("ConductorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conductor");
                });

            modelBuilder.Entity("SistemaFlota.Inspeccion", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("SistemaFlota.Usuario", b =>
                {
                    b.Navigation("Permisos");
                });
#pragma warning restore 612, 618
        }
    }
}
